---
kind: pipeline
name: deploy

steps:
  - name: pre-check
    image: docker
    environment:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      MY_TELEGRAM_TOKEN:
        from_secret: MY_TELEGRAM_TOKEN
      MY_TELEGRAM_ID:
        from_secret: MY_TELEGRAM_ID
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - echo $${DOCKER_PASSWORD}
      - echo $${MY_TELEGRAM_TOKEN}
      - echo $${MY_TELEGRAM_ID}
      - echo $${GITHUB_TOKEN}

  - name: unit-test
    image: node:10
    commands:
      - node test/index.js
    when:
      branch:
        include:
          - feature/*
          - master
          - dev
      event:
        include:
          - push
          - pull_request

  - name: build-branch-image
    image: plugins/docker
    settings:
      repo: allovince/drone-ci-demo
      username: allovince
      password:
        from_secret: DOCKER_PASSWORD
      tag:
        - ${DRONE_BRANCH##feature/}
    when:
      branch: feature/*
      event: push

  - name: build-test-image
    image: plugins/docker
    settings:
      repo: allovince/drone-ci-demo
      username: allovince
      password:
        from_secret: DOCKER_PASSWORD
      tag:
        - test
    when:
      branch: dev
      event: push

  - name: build-staging-image
    image: plugins/docker
    settings:
      repo: allovince/drone-ci-demo
      username: allovince
      password:
        from_secret: DOCKER_PASSWORD
      tag:
        - latest
    when:
      branch: master
      event: pull_request

  - name: semantic-release
    image: gtramontina/semantic-release:15.13.3
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    entrypoint:
      - semantic-release
    when:
      branch: master
      event: push

  - name: build-production-image
    image: plugins/docker
    settings:
      repo: allovince/drone-ci-demo
      username: allovince
      password:
        from_secret: DOCKER_PASSWORD
      tag:
        - ${DRONE_TAG}
    when:
      event: tag
