---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-pv
  namespace: default
  labels:
    alicloud-pvname: drone-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: "your_nas_service"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      alicloud-pvname: drone-pv

